templates:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: "{{ .Release.Name }}"
      namespace: "{{ .Release.Namespace }}"
    subjects:
      - kind: ServiceAccount
        name: "{{ .Values.serviceAccountName }}"
        namespace: arc-runners
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
