env:
  DISCORD_BOT_PREFIX: ">"
  OTLP_LOGS_ENDPOINT: http://alloy-otlp.monitoring.svc.cluster.local:4318/v1/logs
  OTLP_METRICS_ENDPOINT: http://alloy-otlp.monitoring.svc.cluster.local:4318/v1/metrics
  OTLP_TRACES_ENDPOINT: http://alloy-otlp.monitoring.svc.cluster.local:4318/v1/traces
  S3_ENDPOINT: minio.minio.svc.cluster.local

podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: monitoring/openobserve-nodejs

potProvider:
  enable: true
  image: brainicism/bgutil-ytdlp-pot-provider
  port: 4416
