containers:
  studio:
    image: supabase/studio:2025.06.02-sha-8f2993d

  kong:
    image: kong:2.8.1

  auth:
    image: supabase/gotrue:v2.174.0

  rest:
    image: supabase/postgrest:v12.2.12

  realtime:
    image: supabase/realtime:v2.34.47

  storage:
    image: supabase/storage-api:v1.23.0

  imgproxy:
    image: darthsim/imgproxy:v3.8.0

  meta:
    image: supabase/postgres-meta:v0.89.3

  functions:
    image: supabase/edge-runtime:v1.67.4

  analytics:
    image: supabase/logflare:1.12.0

  db:
    image: supabase/postgres:15.8.1.060

  vector:
    image: timberio/vector:0.28.1-alpine

  supavisor:
    image: supabase/supavisor:2.5.1
