name: Deploy AWS

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - "aws/**"
      - .github/workflows/deploy-aws.yaml

  pull_request:
    paths:
      - "aws/**"
      - .github/workflows/deploy-aws.yaml

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: self-hosted

    defaults:
      run:
        working-directory: aws

    outputs:
      has-changes: ${{ steps.summarise.outputs.has-changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run ESlint
        run: npm run lint

      - name: Synthesize
        run: npm run synth

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_CDK_DIFF_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.event.repository.owner }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Determine Deployment Diff
        id: diff
        run: |
          output=$( npm run diff:ci )
          echo "DIFF_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "::group::CDK Diff"
          echo $output
          echo "::endGroup::"

      - name: Summarise Diff
        id: summarise
        uses: actions/github-script@v6
        with:
          script: |
            const lines = process.env.DIFF_OUTPUT.split(/\n/g);
            const added = lines.filter((line) => line.startsWith("[+]")).length;
            const modified = lines.filter((line) => line.startsWith("[~]")).length;
            const removed = lines.filter((line) => line.startsWith("[-]")).length;
            const total = added + modified + removed;
            core.setOutput("has-changes", total > 0 ? "yes" : "no");

            console.log({ added, modified, removed, total });
            core.startGroup("CDK diff output");
            console.log(process.env.DIFF_OUTPUT);
            core.endGroup();

            if (!context.issue.number) {
              return;
            }

            const body = `
            #### CDK Diff Summary
            Added: ${added}
            Modified: ${modified}
            Removed: ${removed}
            Total: ${total}

            <details><summary>Diff output</summary>

            \`\`\`\n
            ${process.env.DIFF_OUTPUT.trim()}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`aws\`, Workflow: \`${{ github.workflow }}\`*
            `.trim();

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });

      - name: Upload artifacts
        if: steps.summarise.outputs.has-changes == 'yes' && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        uses: actions/upload-artifact@v3
        with:
          name: cdk.out
          path: aws/cdk.out

  deploy:
    name: Deploy
    needs: build
    if: needs.build.outputs.has-changes == 'yes' && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment: aws
    runs-on: self-hosted

    defaults:
      run:
        working-directory: aws

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ./aws/.nvmrc

      - name: Install Dependencies
        run: npm install

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cdk.out
          path: aws/cdk.out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_CDK_DEPLOY_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}@${{ github.event.repository.owner }}@${{ github.event.repository.name }}@${{ github.job }}@${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Deploy
        run: npm run deploy:ci
